# Generated by Django 2.1.6 on 2019-02-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task Title', models.CharField(max_length=50)),
                ('Task Description', models.TextField(max_length=200)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
