# Generated by Django 2.1.6 on 2019-02-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task Description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task Title',
            new_name='task_title',
        ),
    ]
