# Generated by Django 4.1.3 on 2022-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
